### ISSUE TITLE
ImportError: No module named 'ruby.logger'

### ISSUE THREAD

**Issue by KokaKiwi** [ZeroEpoch1969/RubyRoseBot#1]
When running `run.py`:

```
Traceback (most recent call last):
  File "run.py", line 157, in main
    from ruby import Ruby
  File "/home/discord/ruby/ruby/__init__.py", line 1, in <module>
    from .bot import Ruby
  File "/home/discord/ruby/ruby/bot.py", line 43, in <module>
    from ruby.playlist import Playlist
  File "/home/discord/ruby/ruby/playlist.py", line 15, in <module>                                                                                                                                 from ruby.logger import log
ImportError: No module named 'ruby.logger'
```

I have all the required python packages installed, and I run it on an Arch Linux with Python 3.5.2

**Comment by script-head** [comment]
Fixed it, the logger.py file wasn't commited.
