### ISSUE TITLE
Music / Data Cache not clearing

### ISSUE THREAD

**Issue by PotatoNoodles** [ZeroEpoch1969/RubyRoseBot#4]
I keep getting this error after a song finishes or when the bot restarts:

WHEN IT RESTARTS:
[WARNING] Failed to clear the music cache!

When a song finishes:
[WARNING] Failed to remove data/music/(Server ID)/(song).mp3

The music then automatically stops and needs a bot restart to fix.

**Comment by script-head** [comment]
It doesn't really matter if it doesn't delete it or not which is why I made it a warning. Check the file permissions because something is stopping it from being deleted.

**Comment by PotatoNoodles** [comment]
I cannot find the issue and once the fail to remove data / cache starts. The bot doesn't play music anymore even if you do (prefix)play (song) it says it registers it, says in the chat it'll play it. Then it odesn't play a thing

**Comment by PotatoNoodles** [comment]
I keep getting this error: OSError: [WinError 6] The handle is invalid
Traceback (most recent call last):
  File "C:\Users\Ben - Gaming\Desktop\PotatoCrew Bot\commands\music.py", line 169, in play
    player = state.voice.create_ffmpeg_player(file_url, stderr=subprocess.PIPE, after=state.toggle_next)
  File "C:\Users\Ben - Gaming\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\voice_client.py", line 431, in create_ffmpeg_player
    p = subprocess.Popen(args, stdin=stdin, stdout=subprocess.PIPE, stderr=stderr)
  File "C:\Users\Ben - Gaming\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 845, in __init__
    _cleanup()
  File "C:\Users\Ben - Gaming\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 505, in _cleanup
    res = inst._internal_poll(_deadstate=sys.maxsize)
  File "C:\Users\Ben - Gaming\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 1256, in _internal_poll
    self.returncode = _GetExitCodeProcess(self._handle)
OSError: [WinError 6] The handle is invalid

**Comment by script-head** [comment]
Install the x86 version of python
